org.gradle.configuration-cache=true

GROUP=io.github.zzangjyj0818
VERSION_NAME=0.1.0

POM_NAME=Spring Transaction Guard
POM_DESCRIPTION=Detects long transactions and synchronous external HTTP calls inside Spring transactions.
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/zzangjyj0818/Spring-Transaction-Guard

POM_LICENSE_NAME=The Apache License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/zzangjyj0818/Spring-Transaction-Guard
POM_SCM_CONNECTION=scm:git:git://github.com/zzangjyj0818/Spring-Transaction-Guard.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/zzangjyj0818/Spring-Transaction-Guard.git

POM_DEVELOPER_ID=zzangjyj0818
POM_DEVELOPER_NAME=Yeon_Jae Jeong
POM_DEVELOPER_URL=https://github.com/zzangjyj0818
